### ISSUE TITLE
Implement Trivia Night feedback

### ISSUE THREAD

**Issue by Bluenix2** [python-discord/sir-robin#8]
This is the follow-up issue from #5 - where the improvements from feedback received of the Trivia Night should be made. See the [Trivia Night feedback Notion page](https://www.notion.so/pythondiscord/Trivia-Night-feedback-ac2173e17d954ee5a16b73e254cff152) (staff only).

## Tasks

- [ ] Remove the [`commands.Bot.fetch_user()`](https://github.com/python-discord/sir-lancebot/blob/96ebaa9ad0917e06afedc2d8bd0a11dcacf16a53/bot/exts/events/trivianight/_scoreboard.py#L46) call to speedup scoreboard. This was found to be the cause of the scoreboard taking an hour to send. The library is following ratelimits and queuing over 100 requests.
- [ ] Edit reminder (1s remaining...) messages instead of continuously sending new ones. In the end it could potentially be outright deleted or edited to some content that makes more sense. Sending new messages caused the content to jump up.
- [ ] Retain answer choice order in the final answer embed and include answer letter. Answers are currently [ordered in the percentage of answers](https://github.com/python-discord/sir-lancebot/blob/96ebaa9ad0917e06afedc2d8bd0a11dcacf16a53/bot/exts/events/trivianight/_questions.py#L128-L137) instead of the same as the question order - this is very confusing for the contestant.
- [ ] Count unanswered questions as the full question time. It is currently possible for someone to answer one question correct super quickly and land the speed leaderboard top spots, which this would fix. The downside is that if someone misses the first few questions they will be heavily penalized, there should be some way of tracking when they started participating.
- [ ] Increase countdown timer before a question from 3 seconds to 5 seconds to give the contestants time to switch to the correct channel.
